import { useEffect, useMemo, useState } from 'react';
import { GeneratedCardCandidate } from './types';

interface GeneratedCardReviewModalProps {
    open: boolean;
    cards: GeneratedCardCandidate[];
    engine: 'gemini' | 'bedrock' | 'fallback';
    fallbackReason?: string;
    loading?: boolean;
    title?: string;
    onClose: () => void;
    onSave: (cards: GeneratedCardCandidate[]) => void;
    onRegenerate?: () => void;
}

function GeneratedCardReviewModal({
    open,
    cards,
    engine,
    fallbackReason,
    loading = false,
    title = 'Review Generated Flashcards',
    onClose,
    onSave,
    onRegenerate,
}: GeneratedCardReviewModalProps) {
    const [draftCards, setDraftCards] = useState<GeneratedCardCandidate[]>([]);

    useEffect(() => {
        if (open) {
            setDraftCards(cards);
        }
    }, [cards, open]);

    const saveDisabled = loading || draftCards.length === 0;

    const engineBadge = useMemo(() => {
        if (engine === 'gemini') {
            return 'Generated by Gemini';
        }
        return 'Fallback generator';
    }, [engine]);

    if (!open) return null;

    return (
        <div className="fixed inset-0 z-[120] bg-black/55 backdrop-blur-sm flex items-center justify-center p-4">
            <div className="w-full max-w-4xl max-h-[85vh] overflow-hidden rounded-2xl border border-[color:var(--color-border)] bg-[color:var(--color-bg-secondary)] flex flex-col">
                <div className="px-6 py-4 border-b border-[color:var(--color-border)] flex items-start justify-between gap-4">
                    <div>
                        <h3 className="text-lg font-semibold">{title}</h3>
                        <div className="text-sm text-[color:var(--color-text-muted)] mt-1">{engineBadge}</div>
                        {fallbackReason && (
                            <div className="text-xs text-amber-400 mt-1">{fallbackReason}</div>
                        )}
                    </div>
                    <button
                        onClick={onClose}
                        className="p-2 rounded-lg hover:bg-[color:var(--color-bg-muted)] transition-colors"
                    >
                        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                <div className="p-4 overflow-y-auto space-y-4">
                    {draftCards.map((card, index) => (
                        <div key={`${index}-${card.front.slice(0, 24)}`} className="rounded-xl border border-[color:var(--color-border)] p-4 bg-[color:var(--color-bg-primary)]">
                            <div className="flex items-center justify-between mb-3">
                                <div className="flex items-center gap-2">
                                    <span className="text-xs px-2 py-1 rounded-md bg-primary-500/10 text-primary-400 uppercase">
                                        {card.type}
                                    </span>
                                    {card.language && (
                                        <span className="text-xs text-[color:var(--color-text-muted)]">{card.language}</span>
                                    )}
                                </div>
                                <button
                                    onClick={() => setDraftCards((prev) => prev.filter((_, i) => i !== index))}
                                    className="text-xs px-2 py-1 rounded-md border border-red-500/30 text-red-400 hover:bg-red-500/10 transition-colors"
                                >
                                    Remove
                                </button>
                            </div>

                            <div className="grid gap-3">
                                <label className="text-sm">
                                    <div className="text-[color:var(--color-text-muted)] mb-1">Front</div>
                                    <textarea
                                        value={card.front}
                                        rows={3}
                                        onChange={(e) => {
                                            const value = e.target.value;
                                            setDraftCards((prev) => prev.map((item, i) => (i === index ? { ...item, front: value } : item)));
                                        }}
                                        className="w-full px-3 py-2 rounded-lg border border-[color:var(--color-border)] bg-[color:var(--color-bg-secondary)]"
                                    />
                                </label>
                                <label className="text-sm">
                                    <div className="text-[color:var(--color-text-muted)] mb-1">Back</div>
                                    <textarea
                                        value={card.back}
                                        rows={3}
                                        onChange={(e) => {
                                            const value = e.target.value;
                                            setDraftCards((prev) => prev.map((item, i) => (i === index ? { ...item, back: value } : item)));
                                        }}
                                        className="w-full px-3 py-2 rounded-lg border border-[color:var(--color-border)] bg-[color:var(--color-bg-secondary)]"
                                    />
                                </label>
                                <label className="text-sm">
                                    <div className="text-[color:var(--color-text-muted)] mb-1">Tags (comma separated)</div>
                                    <input
                                        value={(card.tags || []).join(', ')}
                                        onChange={(e) => {
                                            const tags = e.target.value
                                                .split(',')
                                                .map((tag) => tag.trim())
                                                .filter(Boolean);
                                            setDraftCards((prev) => prev.map((item, i) => (i === index ? { ...item, tags } : item)));
                                        }}
                                        className="w-full px-3 py-2 rounded-lg border border-[color:var(--color-border)] bg-[color:var(--color-bg-secondary)]"
                                    />
                                </label>
                            </div>
                        </div>
                    ))}

                    {!draftCards.length && (
                        <div className="text-center text-[color:var(--color-text-muted)] py-6">
                            No cards selected.
                        </div>
                    )}
                </div>

                <div className="px-6 py-4 border-t border-[color:var(--color-border)] flex items-center justify-between gap-3">
                    <div className="text-xs text-[color:var(--color-text-muted)]">
                        {draftCards.length} card{draftCards.length === 1 ? '' : 's'} ready to save
                    </div>
                    <div className="flex items-center gap-2">
                        {onRegenerate && (
                            <button
                                onClick={onRegenerate}
                                disabled={loading}
                                className="px-3 py-2 rounded-lg border border-[color:var(--color-border)] text-sm hover:bg-[color:var(--color-bg-muted)] disabled:opacity-60 disabled:cursor-not-allowed"
                            >
                                Regenerate
                            </button>
                        )}
                        <button
                            onClick={onClose}
                            className="px-3 py-2 rounded-lg border border-[color:var(--color-border)] text-sm hover:bg-[color:var(--color-bg-muted)]"
                        >
                            Cancel
                        </button>
                        <button
                            onClick={() => onSave(draftCards)}
                            disabled={saveDisabled}
                            className="px-4 py-2 rounded-lg bg-primary-500 text-white text-sm font-medium hover:bg-primary-600 disabled:opacity-60 disabled:cursor-not-allowed"
                        >
                            Save Cards
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default GeneratedCardReviewModal;
