import {
    type LandingPreviewCard,
    type LandingPreviewMode,
    type LandingPreviewScenarioMap,
} from './types';

export const LANDING_PREVIEW_CARDS: LandingPreviewCard[] = [
    {
        mode: 'parsons',
        title: 'Parsons Problem',
        tagline: 'Drag. Drop. Reason.',
        description: 'Put a tiny function back into working order.',
        color: 'text-cyan-500',
        bgColor: 'bg-cyan-500/10',
        borderColor: 'border-cyan-500/30',
    },
    {
        mode: 'surgery',
        title: 'Code Surgery',
        tagline: 'Spot the break.',
        description: 'Click the one line that quietly breaks the result.',
        color: 'text-red-500',
        bgColor: 'bg-red-500/10',
        borderColor: 'border-red-500/30',
    },
    {
        mode: 'eli5',
        title: 'ELI5 Mode',
        tagline: 'Explain simply.',
        description: 'Turn code behavior into plain language a beginner can follow.',
        color: 'text-pink-500',
        bgColor: 'bg-pink-500/10',
        borderColor: 'border-pink-500/30',
    },
    {
        mode: 'mental',
        title: 'Mental Compiler',
        tagline: 'Trace it in your head.',
        description: 'Pick the real output without running the code.',
        color: 'text-violet-500',
        bgColor: 'bg-violet-500/10',
        borderColor: 'border-violet-500/30',
    },
    {
        mode: 'bigo',
        title: 'Big O Battle',
        tagline: 'Name the growth.',
        description: 'Choose the tightest time complexity for a short snippet.',
        color: 'text-orange-500',
        bgColor: 'bg-orange-500/10',
        borderColor: 'border-orange-500/30',
    },
];

export const LANDING_PREVIEW_SCENARIOS = {
    parsons: {
        mode: 'parsons',
        title: 'Build the discount helper',
        prompt: 'Arrange the blocks so the function returns only prices under 20.',
        blocks: [
            { id: 'p1', content: 'def cheap_prices(prices):' },
            { id: 'p2', content: '    cheap = []' },
            { id: 'p3', content: '    for price in prices:' },
            { id: 'p4', content: '        if price < 20:' },
            { id: 'p5', content: '            cheap.append(price)' },
            { id: 'p6', content: '    return cheap' },
        ],
        correctOrder: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
        correctExplanation: 'Nice. The loop checks each price, keeps only values below 20, then returns the collected list.',
        incorrectExplanation: 'Close, but the order matters here: initialize the list before the loop, append inside the condition, and return after the loop finishes.',
        retryLabel: 'Reorder the blocks',
        nextPreviewLabel: 'Next preview: Code Surgery',
    },
    surgery: {
        mode: 'surgery',
        title: 'Patch the score tracker',
        prompt: 'Click the bugged line before the total goes wrong.',
        code: [
            'function addBonus(score) {',
            '  let total = score;',
            '  if (score > 10) {',
            '    total == score + 5;',
            '  }',
            '  return total;',
            '}',
        ].join('\n'),
        bugLine: 4,
        fixSummary: 'Use assignment so the bonus actually updates the total.',
        correctExplanation: 'Exactly. `==` only compares values, so line 4 never changes `total`. Replacing it with `=` applies the bonus.',
        incorrectExplanation: 'Not that one. The bug is on line 4, where the code compares instead of assigning, so the bonus never sticks.',
        retryLabel: 'Scan the code again',
        nextPreviewLabel: 'Next preview: ELI5 Mode',
    },
    eli5: {
        mode: 'eli5',
        title: 'Explain the loop like a coach',
        prompt: 'Explain what this code does without using programmer jargon.',
        code: [
            'total = 0',
            'for snack in snacks:',
            '    total = total + snack',
            'print(total)',
        ].join('\n'),
        minWordCount: 12,
        requiredPhrases: ['add', 'each snack', 'total'],
        forbiddenWords: ['loop', 'iterate', 'variable', 'array'],
        correctExplanation: 'That works. You explained that the computer adds each snack amount into one running total without leaning on jargon.',
        incorrectExplanation: 'Try again with simpler wording. Mention that it adds each snack into a running total, and avoid technical words like `loop` or `variable`.',
        retryLabel: 'Rewrite it simply',
        nextPreviewLabel: 'Next preview: Mental Compiler',
    },
    mental: {
        mode: 'mental',
        title: 'Trace the printed value',
        prompt: 'Pick the output this JavaScript snippet actually prints.',
        code: [
            'let count = 2;',
            'count = count * 3;',
            'console.log(count - 1);',
        ].join('\n'),
        options: ['5', '6', '7'],
        correctOption: '5',
        correctExplanation: 'Right. `count` becomes 6 after multiplication, then the final line prints 5.',
        incorrectExplanation: 'Not quite. First multiply 2 by 3 to get 6, then subtract 1 before printing.',
        retryLabel: 'Trace it one more time',
        nextPreviewLabel: 'Next preview: Big O Battle',
    },
    bigo: {
        mode: 'bigo',
        title: 'Read the growth pattern',
        prompt: 'Choose the tightest time complexity for this search.',
        code: [
            'for item in items:',
            '    if item == target:',
            '        return True',
            'return False',
        ].join('\n'),
        options: ['O(1)', 'O(log n)', 'O(n)'],
        correctComplexity: 'O(n)',
        correctExplanation: 'Correct. In the worst case the code checks every item once, so the work grows linearly with the list size.',
        incorrectExplanation: 'Almost. This is a simple scan through the list, so in the worst case it may inspect every item: `O(n)`.',
        retryLabel: 'Pick another complexity',
        nextPreviewLabel: 'Next preview: Parsons Problem',
    },
} satisfies LandingPreviewScenarioMap;

export const LANDING_PREVIEW_MODE_ORDER: LandingPreviewMode[] = LANDING_PREVIEW_CARDS.map(
    (card) => card.mode,
);
