import type { LearningTrack } from './learningPathTypes';

// ─── 3 Learning Tracks ─────────────────────────────────────────────────────

export const LEARNING_TRACKS: LearningTrack[] = [
    {
        id: 'web-dev',
        title: 'Full-Stack Web Development',
        description: 'From HTML fundamentals to production-grade React apps with Node.js backends.',
        accentColor: '#3B82F6',
        masteredCount: 3,
        totalHours: 42,
        nodes: [
            { id: 'html',   label: 'HTML & CSS',        description: 'Semantic markup, flexbox, grid, responsive design.',       estimatedHours: 3, difficulty: 1, status: 'mastered',     iconType: 'book',   x: 5,  y: 50 },
            { id: 'js',     label: 'JavaScript Core',    description: 'Variables, functions, closures, prototypes, ES6+.',       estimatedHours: 5, difficulty: 2, status: 'mastered',     iconType: 'code',   x: 20, y: 30 },
            { id: 'dom',    label: 'DOM & Events',       description: 'Event loop, delegation, DOM manipulation, fetch API.',    estimatedHours: 3, difficulty: 2, status: 'mastered',     iconType: 'puzzle', x: 20, y: 70 },
            { id: 'react',  label: 'React Fundamentals', description: 'Components, JSX, hooks, state management, lifecycle.',    estimatedHours: 6, difficulty: 3, status: 'in-progress',  iconType: 'code',   x: 40, y: 35 },
            { id: 'ts',     label: 'TypeScript',         description: 'Type system, generics, utility types, strict mode.',      estimatedHours: 4, difficulty: 3, status: 'in-progress',  iconType: 'brain',  x: 40, y: 65 },
            { id: 'node',   label: 'Node.js & Express',  description: 'Server-side JS, REST APIs, middleware, auth.',            estimatedHours: 5, difficulty: 3, status: 'recommended',  iconType: 'rocket', x: 60, y: 30 },
            { id: 'db',     label: 'Databases',          description: 'SQL, NoSQL, ORMs, migrations, query optimization.',       estimatedHours: 4, difficulty: 3, status: 'locked',       iconType: 'puzzle', x: 60, y: 70 },
            { id: 'auth',   label: 'Auth & Security',    description: 'JWT, OAuth, CSRF, XSS prevention, rate limiting.',        estimatedHours: 3, difficulty: 4, status: 'locked',       iconType: 'brain',  x: 75, y: 50 },
            { id: 'deploy', label: 'CI/CD & Deploy',     description: 'Docker, GitHub Actions, Vercel, monitoring.',             estimatedHours: 3, difficulty: 4, status: 'locked',       iconType: 'rocket', x: 90, y: 35 },
            { id: 'cap',    label: 'Capstone Project',   description: 'Build a full-stack app from scratch with all skills.',     estimatedHours: 6, difficulty: 5, status: 'locked',       iconType: 'trophy', x: 90, y: 65 },
        ],
        edges: [
            { from: 'html', to: 'js' }, { from: 'html', to: 'dom' },
            { from: 'js', to: 'react' }, { from: 'js', to: 'ts' },
            { from: 'dom', to: 'react' }, { from: 'dom', to: 'ts' },
            { from: 'react', to: 'node' }, { from: 'ts', to: 'node' },
            { from: 'ts', to: 'db' },
            { from: 'node', to: 'auth' }, { from: 'db', to: 'auth' },
            { from: 'auth', to: 'deploy' }, { from: 'auth', to: 'cap' },
        ],
    },
    {
        id: 'systems',
        title: 'Systems Programming',
        description: 'Low-level fundamentals — memory, concurrency, networking, and OS concepts.',
        accentColor: '#F59E0B',
        masteredCount: 2,
        totalHours: 38,
        nodes: [
            { id: 'c-basics',   label: 'C Fundamentals',     description: 'Pointers, arrays, structs, memory layout.',           estimatedHours: 4, difficulty: 2, status: 'mastered',     iconType: 'code',   x: 5,  y: 50 },
            { id: 'memory',     label: 'Memory Management',  description: 'Stack vs heap, malloc/free, memory leaks, valgrind.', estimatedHours: 4, difficulty: 3, status: 'mastered',     iconType: 'brain',  x: 22, y: 30 },
            { id: 'data-struct', label: 'Data Structures',   description: 'Linked lists, trees, hash tables in C.',              estimatedHours: 5, difficulty: 3, status: 'in-progress',  iconType: 'puzzle', x: 22, y: 70 },
            { id: 'os',         label: 'OS Concepts',        description: 'Processes, threads, scheduling, virtual memory.',      estimatedHours: 5, difficulty: 4, status: 'recommended',  iconType: 'book',   x: 42, y: 35 },
            { id: 'concurrency', label: 'Concurrency',       description: 'Mutexes, semaphores, deadlocks, thread pools.',       estimatedHours: 4, difficulty: 4, status: 'locked',       iconType: 'brain',  x: 42, y: 65 },
            { id: 'networking', label: 'Networking',          description: 'Sockets, TCP/UDP, HTTP, DNS, TLS.',                   estimatedHours: 4, difficulty: 3, status: 'locked',       iconType: 'rocket', x: 62, y: 30 },
            { id: 'fs',         label: 'File Systems',       description: 'Inodes, journaling, FUSE, block devices.',             estimatedHours: 3, difficulty: 4, status: 'locked',       iconType: 'puzzle', x: 62, y: 70 },
            { id: 'rust',       label: 'Rust Intro',         description: 'Ownership, borrowing, lifetimes, cargo.',              estimatedHours: 5, difficulty: 4, status: 'locked',       iconType: 'code',   x: 80, y: 50 },
            { id: 'cap-sys',    label: 'Build a Shell',      description: 'Implement a Unix shell with pipes and redirects.',     estimatedHours: 4, difficulty: 5, status: 'locked',       iconType: 'trophy', x: 95, y: 50 },
        ],
        edges: [
            { from: 'c-basics', to: 'memory' }, { from: 'c-basics', to: 'data-struct' },
            { from: 'memory', to: 'os' }, { from: 'memory', to: 'concurrency' },
            { from: 'data-struct', to: 'os' }, { from: 'data-struct', to: 'concurrency' },
            { from: 'os', to: 'networking' }, { from: 'os', to: 'fs' },
            { from: 'concurrency', to: 'networking' }, { from: 'concurrency', to: 'fs' },
            { from: 'networking', to: 'rust' }, { from: 'fs', to: 'rust' },
            { from: 'rust', to: 'cap-sys' },
        ],
    },
    {
        id: 'ml-ai',
        title: 'Machine Learning & AI',
        description: 'From Python data science to deep learning and production ML pipelines.',
        accentColor: '#8B5CF6',
        masteredCount: 2,
        totalHours: 45,
        nodes: [
            { id: 'python',     label: 'Python for Data',    description: 'NumPy, Pandas, Matplotlib, Jupyter notebooks.',        estimatedHours: 4, difficulty: 1, status: 'mastered',     iconType: 'code',   x: 5,  y: 50 },
            { id: 'stats',      label: 'Statistics',         description: 'Probability, distributions, hypothesis testing.',       estimatedHours: 4, difficulty: 2, status: 'mastered',     iconType: 'book',   x: 20, y: 30 },
            { id: 'lin-alg',    label: 'Linear Algebra',     description: 'Vectors, matrices, eigenvalues, SVD.',                 estimatedHours: 3, difficulty: 2, status: 'in-progress',  iconType: 'brain',  x: 20, y: 70 },
            { id: 'ml-basics',  label: 'ML Fundamentals',    description: 'Regression, classification, cross-validation, bias.',  estimatedHours: 5, difficulty: 3, status: 'recommended',  iconType: 'puzzle', x: 40, y: 35 },
            { id: 'sklearn',    label: 'Scikit-Learn',       description: 'Pipelines, feature engineering, model selection.',      estimatedHours: 4, difficulty: 3, status: 'locked',       iconType: 'code',   x: 40, y: 65 },
            { id: 'dl',         label: 'Deep Learning',      description: 'Neural networks, backprop, CNNs, RNNs.',               estimatedHours: 6, difficulty: 4, status: 'locked',       iconType: 'brain',  x: 60, y: 30 },
            { id: 'nlp',        label: 'NLP',                description: 'Tokenization, embeddings, transformers, BERT.',         estimatedHours: 5, difficulty: 4, status: 'locked',       iconType: 'book',   x: 60, y: 70 },
            { id: 'mlops',      label: 'MLOps',              description: 'Model serving, monitoring, A/B testing, pipelines.',    estimatedHours: 4, difficulty: 4, status: 'locked',       iconType: 'rocket', x: 80, y: 35 },
            { id: 'llm',        label: 'LLMs & RAG',        description: 'Fine-tuning, prompt engineering, RAG, agents.',         estimatedHours: 5, difficulty: 5, status: 'locked',       iconType: 'rocket', x: 80, y: 65 },
            { id: 'cap-ml',     label: 'End-to-End ML App',  description: 'Build and deploy a full ML application.',               estimatedHours: 5, difficulty: 5, status: 'locked',       iconType: 'trophy', x: 95, y: 50 },
        ],
        edges: [
            { from: 'python', to: 'stats' }, { from: 'python', to: 'lin-alg' },
            { from: 'stats', to: 'ml-basics' }, { from: 'lin-alg', to: 'ml-basics' },
            { from: 'lin-alg', to: 'sklearn' },
            { from: 'ml-basics', to: 'dl' }, { from: 'ml-basics', to: 'nlp' },
            { from: 'sklearn', to: 'dl' }, { from: 'sklearn', to: 'nlp' },
            { from: 'dl', to: 'mlops' }, { from: 'dl', to: 'llm' },
            { from: 'nlp', to: 'llm' },
            { from: 'mlops', to: 'cap-ml' }, { from: 'llm', to: 'cap-ml' },
        ],
    },
];
