import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';

// Terms of Service page
function TermsPage() {
    const lastUpdated = 'January 14, 2026';

    const sections = [
        {
            title: '1. Acceptance of Terms',
            content: `
                <p>By accessing or using SocraticDev ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of the terms, you may not access the Service.</p>
                <p>These Terms apply to all visitors, users, and others who access or use the Service. By using the Service, you represent that you are at least 13 years of age and have the legal capacity to enter into these Terms.</p>
            `
        },
        {
            title: '2. Description of Service',
            content: `
                <p>SocraticDev is an AI-powered educational platform designed to help developers learn programming concepts through the Socratic method. The Service includes:</p>
                <ul>
                    <li><strong>AI Chat Assistant:</strong> An AI-powered tutor that helps you understand code through questions and explanations</li>
                    <li><strong>The Dojo:</strong> Interactive coding challenges for deliberate practice</li>
                    <li><strong>Code Visualizer:</strong> Tools to visualize code execution and dependencies</li>
                    <li><strong>Spaced Repetition System:</strong> Flashcards for long-term retention</li>
                    <li><strong>Analytics & Gamification:</strong> Progress tracking and achievement systems</li>
                </ul>
            `
        },
        {
            title: '3. User Responsibilities',
            content: `
                <h4>3.1 API Key</h4>
                <p>To use SocraticDev, you must provide your own Google Gemini API key. You are responsible for:</p>
                <ul>
                    <li>Obtaining a valid API key from Google AI Studio</li>
                    <li>Keeping your API key secure and confidential</li>
                    <li>All charges incurred through your API key usage</li>
                    <li>Complying with Google's terms of service</li>
                </ul>

                <h4>3.2 Acceptable Use</h4>
                <p>You agree NOT to use the Service to:</p>
                <ul>
                    <li>Generate malicious code, malware, or security exploits</li>
                    <li>Violate any applicable laws or regulations</li>
                    <li>Harass, abuse, or harm another person</li>
                    <li>Impersonate any person or entity</li>
                    <li>Interfere with or disrupt the Service</li>
                    <li>Attempt to gain unauthorized access to any systems</li>
                    <li>Use the Service for any commercial purposes without authorization</li>
                </ul>
            `
        },
        {
            title: '4. Intellectual Property',
            content: `
                <h4>4.1 Our Content</h4>
                <p>The Service and its original content (excluding user-generated content), features, and functionality are and will remain the exclusive property of SocraticDev and its licensors. The Service is protected by copyright, trademark, and other laws.</p>

                <h4>4.2 Your Content</h4>
                <p>You retain ownership of any code, messages, or content you submit to the Service. By submitting content, you grant us a limited license to process your content solely for the purpose of providing the Service.</p>

                <h4>4.3 AI-Generated Content</h4>
                <p>Content generated by our AI assistant is provided for educational purposes. You may use AI-generated code in your own projects, but you acknowledge that:</p>
                <ul>
                    <li>AI-generated code may contain errors or security vulnerabilities</li>
                    <li>You are responsible for reviewing and testing any code before use</li>
                    <li>We make no warranties about the accuracy or suitability of AI-generated content</li>
                </ul>
            `
        },
        {
            title: '5. Disclaimers',
            content: `
                <h4>5.1 "As Is" Service</h4>
                <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We disclaim all warranties, express or implied, including but not limited to:</p>
                <ul>
                    <li>Merchantability and fitness for a particular purpose</li>
                    <li>Non-infringement</li>
                    <li>Accuracy or completeness of content</li>
                    <li>Uninterrupted or error-free operation</li>
                </ul>

                <h4>5.2 Educational Purpose Only</h4>
                <p>SocraticDev is an educational tool. The AI responses and code suggestions are intended for learning purposes and should not be considered professional advice. Always consult with qualified professionals for production systems.</p>

                <h4>5.3 Third-Party Services</h4>
                <p>The Service relies on third-party services (including Google Gemini API). We are not responsible for the availability, accuracy, or performance of these third-party services.</p>
            `
        },
        {
            title: '6. Limitation of Liability',
            content: `
                <p>To the maximum extent permitted by law, SocraticDev and its affiliates, officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to:</p>
                <ul>
                    <li>Loss of profits, data, or other intangible losses</li>
                    <li>Damages resulting from your use or inability to use the Service</li>
                    <li>Damages resulting from unauthorized access to your data</li>
                    <li>Damages resulting from third-party services or content</li>
                </ul>
                <p>Our total liability shall not exceed the amount you paid us (if any) in the 12 months preceding the claim.</p>
            `
        },
        {
            title: '7. Indemnification',
            content: `
                <p>You agree to defend, indemnify, and hold harmless SocraticDev and its affiliates from any claims, damages, losses, or expenses (including reasonable attorneys' fees) arising from:</p>
                <ul>
                    <li>Your use of the Service</li>
                    <li>Your violation of these Terms</li>
                    <li>Your violation of any third-party rights</li>
                    <li>Any content you submit to the Service</li>
                </ul>
            `
        },
        {
            title: '8. Modifications to Service',
            content: `
                <p>We reserve the right to modify, suspend, or discontinue the Service (or any part thereof) at any time, with or without notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuation of the Service.</p>
            `
        },
        {
            title: '9. Changes to Terms',
            content: `
                <p>We reserve the right to modify these Terms at any time. We will notify users of significant changes by updating the "Last Updated" date. Your continued use of the Service after any changes constitutes acceptance of the new Terms.</p>
            `
        },
        {
            title: '10. Governing Law',
            content: `
                <p>These Terms shall be governed by and construed in accordance with the laws of the State of California, United States, without regard to its conflict of law provisions. Any disputes arising from these Terms or the Service shall be resolved in the courts of San Francisco County, California.</p>
            `
        },
        {
            title: '11. Contact Information',
            content: `
                <p>If you have any questions about these Terms, please contact us at:</p>
                <ul>
                    <li>Email: <a href="mailto:legal@socraticdev.com" class="text-primary-500 hover:underline">legal@socraticdev.com</a></li>
                </ul>
            `
        }
    ];

    return (
        <div className="min-h-screen bg-[color:var(--color-bg-primary)]">
            <Navbar />

            <main className="pt-24 pb-20">
                <div className="container-custom max-w-4xl">
                    {/* Header */}
                    <div className="mb-12">
                        <h1 className="font-display text-display-md font-bold mb-4">
                            Terms of Service
                        </h1>
                        <p className="text-[color:var(--color-text-muted)]">
                            Last updated: {lastUpdated}
                        </p>
                    </div>

                    {/* Introduction */}
                    <div className="p-6 rounded-xl bg-[color:var(--color-bg-secondary)] border border-[color:var(--color-border)] mb-8">
                        <p className="text-[color:var(--color-text-secondary)]">
                            Please read these Terms of Service carefully before using SocraticDev. These Terms govern
                            your access to and use of our AI-powered learning platform. By accessing or using the Service,
                            you agree to be bound by these Terms.
                        </p>
                    </div>

                    {/* Table of Contents */}
                    <div className="p-6 rounded-xl bg-[color:var(--color-bg-secondary)] border border-[color:var(--color-border)] mb-12">
                        <h2 className="font-semibold mb-4">Table of Contents</h2>
                        <ul className="grid md:grid-cols-2 gap-2">
                            {sections.map((section) => (
                                <li key={section.title}>
                                    <a href={`#${section.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`} className="text-primary-500 hover:underline text-sm">
                                        {section.title}
                                    </a>
                                </li>
                            ))}
                        </ul>
                    </div>

                    {/* Sections */}
                    <div className="space-y-10">
                        {sections.map((section) => (
                            <section key={section.title} id={section.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}>
                                <h2 className="font-display text-xl font-bold mb-4">{section.title}</h2>
                                <div
                                    className="prose prose-invert max-w-none text-[color:var(--color-text-secondary)] [&_h4]:font-semibold [&_h4]:text-[color:var(--color-text-primary)] [&_h4]:mt-4 [&_h4]:mb-2 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1 [&_li]:text-[color:var(--color-text-secondary)] [&_p]:mb-3"
                                    dangerouslySetInnerHTML={{ __html: section.content }}
                                />
                            </section>
                        ))}
                    </div>
                </div>
            </main>

            <Footer />
        </div>
    );
}

export default TermsPage;
